services:
  scribe-service:
    build: ./scribe-service
    working_dir: /scribe-service/scribe-service
    volumes:
      - .:/scribe-service
      - transcribe-cache:/root/.cache
      - transcribe-venv:/opt/conda/lib/python3.11/site-packages/transcribe_anything/venv
      - ffmpeg-bin:/opt/conda/lib/python3.11/site-packages/static_ffmpeg/bin
    expose:
      - 8001
    deploy:
      resources:
        reservations:
          devices:
            - capabilities: [ gpu ]
    environment:
      POSTGRES_HOST: scribe-db:5432
      POSTGRES_USER: scribe
      POSTGRES_PASSWORD: password
      POSTGRES_DB: database
      DEVICE: insane # options: cpu, cuda, insane, ...
      HF_TOKEN: None # replace with your actual Hugging Face token or None
    depends_on:
      scribe-db:
        condition: service_healthy

  scribe-db:
    image: postgres:15.2
    environment:
      POSTGRES_USER: scribe
      POSTGRES_PASSWORD: password
      POSTGRES_DB: database
    expose:
      - 5432
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U scribe -d database"]
      interval: 5s
      timeout: 5s
      retries: 10
    volumes:
      - scribe-db-data:/var/lib/postgresql/data

  api-gateway:
    build: ./api-gateway
    working_dir: /api-gateway/api-gateway
    volumes:
      - .:/api-gateway
    ports:
      - 8000:8000
    environment:
      SCRIBE_SERVICE_URL: http://scribe-service:8001
    depends_on:
      - scribe-service

  frontend:
    build: ./frontend
    environment:
      REACT_APP_API_GATEWAY_URL: http://localhost:8000
      REACT_APP_API_GATEWAY_WS_URL: ws://localhost:8000
      WATCHPACK_POLLING: true
    volumes:
      - ./frontend:/frontend
    ports:
      - 3000:3000
    depends_on:
      - api-gateway


volumes:
  scribe-db-data:
  transcribe-venv:
  transcribe-cache:
  ffmpeg-bin:
